LMC_Other_MVC/Controllers/LMC_PrintStringLog_GetPrintStringsByPalletController.cs
using LMC_Other_InventoryData;
using LMC_Other_InventoryData.DB_Models;
using LMC_Other_MVC.Models;
using Microsoft.AspNetCore.Mvc;
using static System.Net.WebRequestMethods;
using System;
using Serilog;

namespace LMC_Other_MVC.Controllers
{
    public class LMC_PrintStringLog_GetPrintStringsByPalletController : Controller
    {
        // Declaring a private readonly field for the repository
        private readonly LMC_PrintStringLog_GetPrintStringsByPallet_Repo _repo;

        // Passing an instance of the repository through dependency injection
        public LMC_PrintStringLog_GetPrintStringsByPalletController(LMC_PrintStringLog_GetPrintStringsByPallet_Repo repo)
        {
            // Assigning the provided repository instance to the private field
            _repo = repo;
        }

        [HttpGet] // HTTP GET action method for handling requests to the Index page
        public IActionResult Index(string? palletNumber)
        {
            try
            {
                // Checking if palletNumber is null or empty or contains only whitespaces
                if (string.IsNullOrWhiteSpace(palletNumber))
                {
                    // Setting palletNumber to empty string if null, empty, or contains only whitespaces
                    palletNumber = string.Empty;
                }

                // Calling the repository method to get print strings by pallet
                List<LMC_PrintStringLog_GetPrintStringsByPallet_Model> lPrintStringLog_GetPrintStringsByPallet = _repo.GetPrintStringsByPallet(palletNumber);

                // Creating a view model instance to pass data to the view
                LMC_PrintStringLog_GetPrintStringsByPallet_VM oPrintStringLog_GetPrintStringsByPallet = new()
                {
                    lo_PrintStringLog_GetPrintStringsByPallet = lPrintStringLog_GetPrintStringsByPallet,
                    PalletNumber = palletNumber
                };

                // Returning the view along with the populated view model
                return View(oPrintStringLog_GetPrintStringsByPallet);
            }
            catch (Exception ex)
            {
                //Log error message to text file
                Log.Error("Error", ex.Message, ex.StackTrace);

                // Returning null in case of an exception
                return null;
            }
        }
    }
}

LMC_Other_MVC/Views/LMC_PrintStringLog_GetPrintStringsByPallet/Index.cshtml
@model LMC_PrintStringLog_GetPrintStringsByPallet_VM

@{
    ViewData["Title"] = "String Logs By Pallet";
}

<div class="container mt-4">

    <h2 class="text-center">String Logs By Pallet</h2>

    <form asp-controller="LMC_PrintStringLog_GetPrintStringsByPallet" asp-action="Index" method="get">
        <div class="row">
            <div class="col-md-6">
                <label asp-for="PalletNumber" class="form-label">Pallet Number:</label>
                <input asp-for="PalletNumber" type="text" class="form-control" value="@Model.PalletNumber" />
                <span asp-validation-for="PalletNumber" class="text-danger"></span>
            </div>
        </div>

        <button type="submit" class="btn btn-primary mt-2">Submit</button>

    </form>

    <div class="table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <th>Pk Print String Log ID</th>
                    <th>Serial No</th>
                    <th>Product No</th>
                    <th>Pallet No</th>
                    <th>Scale Name</th>
                    <th>Scale ID</th>
                    <th>Insert Date</th>
                    <th>Print String</th>
                </tr>
            </thead>

            <tbody>
                @if (Model.lo_PrintStringLog_GetPrintStringsByPallet.Count == 0)
                {
                    <tr>
                        <td colspan="7">No data available</td>
                    </tr>
                }
                else
                {
                    @foreach (var item in Model.lo_PrintStringLog_GetPrintStringsByPallet)
                    {
                        <tr>
                            <td>@item.pkPrintStringLogID</td>
                            <td>@item.SerialNumber</td>
                            <td>@item.ProductNumber</td>
                            <td>@item.PalletNumber</td>
                            <td>@item.ScaleName</td>
                            <td>@item.ScaleID</td>
                            <td>@item.InsertDate</td>
                            <td>@item.PrintString</td>
                        </tr>
                    }

                }
            </tbody>
        </table>

    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}