LMC_Other_MVC/Controllers/LMC_PalletExact_GetPalletExactSummaryLastLabelDateController.cs
using LMC_Other_InventoryData;
using LMC_Other_InventoryData.DB_Models;
using Microsoft.AspNetCore.Mvc;
using Serilog;

namespace LMC_Other_MVC.Controllers
{
    public class LMC_PalletExact_GetPalletExactSummaryLastLabelDateController : Controller
    {
        // Declaring a private readonly field for the repository
        private readonly LMC_PalletExact_GetPalletExactSummaryLastLabelDate_Repo _repo;

        // Passing an instance of the repository through dependency injection
        public LMC_PalletExact_GetPalletExactSummaryLastLabelDateController(LMC_PalletExact_GetPalletExactSummaryLastLabelDate_Repo repo)
        {
            // Assigning the provided repository instance to the private field
            _repo = repo;
        }

        [HttpGet] // HTTP GET action method for handling requests to the Index page
        public async Task<IActionResult> Index(string productNumber, DateTime? runStartDate, DateTime? runEndDate)
        {
            try
            {
                // Use null-coalescing operator to set default values if not provided
                runStartDate ??= DateTime.Now;
                runEndDate ??= DateTime.Now;

                // Calling the repository method to get pallet exact summary with the last label date
                LMC_PalletExact_GetPalletExactSummaryLastLabelDate_Model result = await _repo.GetPalletExactSummaryLastLabelDate(productNumber, (DateTime)runStartDate, (DateTime)runEndDate);

                // Check if the result is null or if the LastLabelDate is DateTime.MinValue
                if (result != null && result.LastLabelDate != DateTime.MinValue)
                {
                    // Returning the view along with the result
                    return View(result);
                }
                else
                {
                    // Log the case where no data is available
                    Log.Information("No data available for the selected data range");

                    // Return a view for the case where no data is available
                    return View("NoDataView"); 
                }

            }
            catch (Exception ex)
            {
                //Log error message to text file
                Log.Error("Error", ex.Message, ex.StackTrace);

                // Return null in case of an exception
                return null; 
            }

        }
    }
}

LMC_Other_MVC/Views/LMC_PalletExact_GetPalletExactSummaryLastLabelDate/Index.cshtml
@model LMC_Other_InventoryData.DB_Models.LMC_PalletExact_GetPalletExactSummaryLastLabelDate_Model

@{
    ViewData["Title"] = "Last Label Date";
}

<div class="container mt-4">

    <h2 class="text-center mb-4">Get Last Label Date</h2>

    <form asp-controller="LMC_PalletExact_GetPalletExactSummaryLastLabelDate" asp-action="Index" method="get">
        <div class="row">
            <div class="col-md-4">
                <label asp-for="ProductNumber" class="form-label fst-italic">Product Number:</label>
                <input asp-for="ProductNumber" type="text" class="form-control" required />
            </div>
            <div class="col-md-4">
                <label asp-for="RunStartDate" class="form-label fst-italic">Start Date:</label>
                <input asp-for="RunStartDate" type="date" class="form-control" value="@Model?.RunStartDate.ToString("yyyy-MM-dd") ?? string.Empty)" required />
            </div>

            <div class="col-md-4">
                <label asp-for="RunEndDate" class="form-label fst-italic">End Date:</label>
                <input asp-for="RunEndDate" type="date" class="form-control" value="@Model?.RunEndDate.ToString("yyyy-MM-dd") ?? string.Empty)" required />
            </div>
        </div>

        <div>
            <button type="submit" class="btn btn-primary mt-2">Apply data rage</button>
        </div>
    </form>

    @if (Model != null)
    {
        <div>
            <h3>Result:</h3>
            <p>Last Label Date: @Model.LastLabelDate.ToString("yyyy-MM-dd HH:mm:ss")</p>
        </div>
    }
    else
    {
        <div>
            <p>No data available for the selected data range</p>
        </div>
    }


</div>

LMC_Other_MVC/Views/LMC_PalletExact_GetPalletExactSummaryLastLabelDate/NoDataView.cshtml
@model LMC_Other_InventoryData.DB_Models.LMC_PalletExact_GetPalletExactSummaryLastLabelDate_Model

<div>
    <h3>No Data Available</h3>
    <p>No data available for the selected data range.</p>
</div>