LMC_Other_MVC/Controllers/LMC_LabelCounter_GetUploadLabelCounterRecordsController.cs
using LMC_Other_InventoryData;
using LMC_Other_InventoryData.DB_Models;
using LMC_Other_MVC.Models;
using Microsoft.AspNetCore.Mvc;
using Serilog;

namespace LMC_Other_MVC.Controllers
{
    public class LMC_LabelCounter_GetUploadLabelCounterRecordsController : Controller
    {
        // Declaring a private readonly field for the repository
        private readonly LMC_LabelCounter_GetUploadLabelCounterRecords_Repo _repo;

        // Passing an instance of the repository through dependency injection
        public LMC_LabelCounter_GetUploadLabelCounterRecordsController(LMC_LabelCounter_GetUploadLabelCounterRecords_Repo repo)
        {
            // Assigning the provided repository instance to the private field
            _repo = repo;
        }

        [HttpGet]  // HTTP GET action method for handling requests to the Index page
        public IActionResult Index(DateTime? startDate, DateTime? endDate)
        {
            try
            {
                // Checking if either startDate or endDate is null
                if (startDate == null || endDate == null)
                {
                    endDate = DateTime.Now; // Setting endDate to the current date and time if null
                    startDate = DateTime.Now;  // Setting startDate to the current date and time if null
                }

                // Calling the repository method to get label counter records within the specified date range
                List<LMC_LabelCounter_GetUploadLabelCounterRecords_Model> lLabelCounterRecords = _repo.GetUploadLabelCounterRecords_Repos(startDate, endDate);

                // Creating a view model instance to pass data to the view
                LMC_LabelCounter_GetUploadLabelCounterRecords_VM oLabelCounterRecordVM = new LMC_LabelCounter_GetUploadLabelCounterRecords_VM();

                // Assigning values to the view model properties
                oLabelCounterRecordVM.StartDate = startDate.Value;
                oLabelCounterRecordVM.EndDate = endDate.Value;
                oLabelCounterRecordVM.loLabelCounterRecords = lLabelCounterRecords;

                // Returning the view along with the populated view model
                return View(oLabelCounterRecordVM);
            }
            catch (Exception ex)
            {
                //Log error message to text file
                Log.Error("Error", ex.Message, ex.StackTrace);

                // Returning null in case of an exception
                return null; 
            }

        }
    }
}

LMC_Other_MVC/Views/LMC_LabelCounter_GetUploadLabelCounterRecords/Index.cshtml
@model LMC_LabelCounter_GetUploadLabelCounterRecords_VM

@{
    ViewData["Title"] = "Label Counter Records";
}


<div class="container mt-4">

    <h2 class="text-center">Label Counter Rrecords
    </h2> 

    <form asp-controller="LMC_LabelCounter_GetUploadLabelCounterRecords" asp-action="Index" method="get">
        <div class="row">
            <div class="col-md-6">
                <label asp-for="StartDate" class="form-label fst-italic">Start Date:</label>
                <input asp-for="StartDate" type="date" class="form-control" value="@Model.StartDate.ToString("yyyy-MM-dd")" />
            </div>
            <div class="col-md-6">
                <label asp-for="EndDate" class="form-label fst-italic">End Date:</label>
                <input asp-for="EndDate" type="date" class="form-control" value="@Model.EndDate.ToString("yyyy-MM-dd")" />
            </div>
        </div>
        <button type="submit" class="btn btn-primary mt-2">Apply date range</button>
    </form>


    <div class="table-responsibe">
        <table class="table">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Scale Name</th>
                    <th>Scale ID</th>
                    <th>Variation No</th>
                    <th>Product No</th>
                    <th>Count Good</th>
                    <th>Count Bad</th>
                    <th>Start Date Time</th>
                    <th>End Date Time</th>
                    <th>Exported Date</th>
                    <th>Insert Date</th>
                    <th>Modified Date</th>
                    <th>Exported</th>
                </tr>
            </thead>
            <tbody>
                @if (Model.loLabelCounterRecords.Count == 0)
                {
                    <tr>
                        <td colspan="7">No data available for the selected data range</td>
                    </tr>
                }
                else
                {
                    @foreach (var item in Model.loLabelCounterRecords)
                    {
                        <tr>
                            <td>@item.pkLabelCounterID</td>
                            <td>@item.ScaleName</td>
                            <td>@item.ScaleID</td>
                            <td>@item.VariationNo</td>
                            <td>@item.ProductNo</td>
                            <td>@item.CountGood</td>
                            <td>@item.CountBad</td>
                            <td>@item.StartDateTime</td>
                            <td>@item.EndDateTime</td>
                            <td>@item.Exported</td>
                            <td>@item.InsertDate</td>
                            <td>@item.ModifiedDate</td>
                            <td>
                                @if (item.Exported.HasValue)
                                {
                                    @(item.Exported.Value ? "Yes" : "No")
                                }
                                else
                                {
                                    @("N/A")
                                }
                            </td>
                        </tr>

                    }
                }

            </tbody>
        </table>

    </div>
</div>