LMC_Other_MVC/Controllers/LMC_InvData_RecordDetailController.cs
using LMC_Other_InventoryData;
using LMC_Other_InventoryData.DB_Models;
using LMC_Other_MVC.Models;
using Microsoft.AspNetCore.Mvc;
using Serilog;

namespace LMC_Other_MVC.Controllers
{
    public class LMC_InvData_RecordDetailController : Controller
    {
        // Declaring a private readonly field for the repository
        private readonly LMC_InvData_RecordDetail_Repo _repo;

        // Passing an instance of the repository through dependency injection
        public LMC_InvData_RecordDetailController(LMC_InvData_RecordDetail_Repo repo)
        {
            // Assigning the provided repository instance to the private field
            _repo = repo;
        }

        [HttpGet] // HTTP GET action method for handling requests to the Index page
        public IActionResult Index(string? serialNumber, string? scaleID)
        {

            try
            {
                // Checking if either serialNumber or scaleID is null or empty
                if (string.IsNullOrEmpty(serialNumber) || string.IsNullOrEmpty(scaleID))
                {
                    serialNumber = string.Empty; 
                    scaleID = string.Empty;    
                }

                // Calling the repository method to get inventory record details based on serialNumber and scaleID
                List<LMC_InvData_RecordDetail_Model> lInvDataRecordDetails = string.IsNullOrEmpty(serialNumber) 
                    ? new List<LMC_InvData_RecordDetail_Model>()   // Creating an empty list if serialNumber is null or empty
                    : _repo.Get_Inventory_Record_Detail(serialNumber, scaleID);

                // Creating a view model instance to pass data to the view
                LMC_InvData_RecordDetail_VM oInvDataRecordDetailVM = new()
                {
                    ScaleID = scaleID,
                    SerialNumber = serialNumber,
                    Lo_InvData_RecordDetails = lInvDataRecordDetails
                };

                // Returning the view along with the populated view model
                return View(oInvDataRecordDetailVM);
            }
            catch (Exception ex)
            {
                //Log error message to text file
                Log.Error("Error", ex.Message, ex.StackTrace);

                // Returning null in case of an exception
                return null; 
            }

        }
    }
}

LMC_Other_MVC/Controllers/LMC_InventoryDataController.cs
using LMC_Other_InventoryData;
using LMC_Other_InventoryData.DB_Models;
using LMC_Other_MVC.Models;
using Microsoft.AspNetCore.Mvc;
using Serilog;

namespace LMC_Other_MVC.Controllers
{
    public class LMC_InventoryDataController : Controller
    {
        // Declaring a private readonly field for the repository
        private readonly LMC_InventoryData_Repo _repo;

        // Passing an instance of the repository through dependency injection
        public LMC_InventoryDataController(LMC_InventoryData_Repo repo)
        {
            // Assigning the provided repository instance to the private field
            _repo = repo;
        }

        [HttpGet] // HTTP GET action method for handling requests to the Index page
        public IActionResult Index(DateTime? startDate, DateTime? endDate)
        {
            try
            {
                // Checking if either startDate or endDate is null
                if (startDate == null || endDate == null) 
                {
                    endDate = DateTime.Now; // Setting endDate to the current date and time if null
                    startDate = endDate.Value.AddDays(-30); // Setting startDate to 30 days before endDate

                }

                // Calling the repository method to get exported inventory data within the specified date range
                List<LMC_InventoryData_Model> lInvDataExported = _repo.Get_InventoryData_Exported(startDate.Value, endDate.Value);

                // Creating a view model instance to pass data to the view
                LMC_InventoryData_VM oInvDataVM = new LMC_InventoryData_VM();

                // Assigning values to the view model properties
                oInvDataVM.StartDate = startDate.Value;
                oInvDataVM.EndDate = endDate.Value;
                oInvDataVM.loInvDataExp = lInvDataExported;

                // Returning the view along with the populated view model
                return View(oInvDataVM);
            }
            catch (Exception ex)
            {
                //Log error message to text file
                Log.Error("Error", ex.Message, ex.StackTrace);

                // Returning null in case of an exception
                return null; 
            }

        }
    }
}

LMC_Other_MVC/Controllers/LMC_Pallet_GetNonCollectedController.cs
using LMC_Other_InventoryData;
using LMC_Other_InventoryData.DB_Models;
using LMC_Other_MVC.Models;
using Microsoft.AspNetCore.Mvc;
using Serilog;

namespace LMC_Other_MVC.Controllers
{
    public class LMC_Pallet_GetNonCollectedController : Controller
    {
        // Declaring a private readonly field for the repository
        private readonly LMC_Pallet_GetNonCollected_Repo _repo;

        // Passing an instance of the repository through dependency injection
        public LMC_Pallet_GetNonCollectedController(LMC_Pallet_GetNonCollected_Repo repo)
        {
            // Assigning the provided repository instance to the private field
            _repo = repo;
        }

        [HttpGet] // HTTP GET action method for handling requests to the Index page
        public IActionResult Index()
        {
            try
            {
                // Checking if the model state is not valid
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }

                // Getting a list of non-collected items from the repository
                List<LMC_Pallet_GetNonCollected_Model> lGetNonCollected_From_Repo = _repo.GetNonCollected();

                // Creating a view model for non-collected items instance to pass data to the view
                LMC_Pallet_GetNonCollected_VM oNonCollected_VM = new LMC_Pallet_GetNonCollected_VM();

                // Assigning the list of non-collected items to the view model
                oNonCollected_VM.lNonCollected_From_VM = lGetNonCollected_From_Repo;

                // Returning the Index view with the non-collected items view model
                return View(oNonCollected_VM);
            }
            catch (Exception ex)
            {
                //Log error message to text file
                Log.Error("Error", ex.Message, ex.StackTrace);

                // Returning null in case of an exception
                return null; 
            }
        }
    }
}

LMC_Other_MVC/Controllers/LMC_Pallet_GetPalletRecordsController.cs
using LMC_Other_InventoryData;
using LMC_Other_InventoryData.DB_Models;
using LMC_Other_MVC.Models;
using Microsoft.AspNetCore.Mvc;
using Serilog;

namespace LMC_Other_MVC.Controllers
{
    public class LMC_Pallet_GetPalletRecordsController : Controller
    {
        // Declaring a private readonly field for the repository
        private readonly LMC_Pallet_GetPalletRecords_Repo _repo;

        // Passing an instance of the repository through dependency injection
        public LMC_Pallet_GetPalletRecordsController(LMC_Pallet_GetPalletRecords_Repo repo)
        {
            // Assigning the provided repository instance to the private field
            _repo = repo;
        }

        [HttpGet] // HTTP GET action method for handling requests to the Index page
        public IActionResult Index(string? serialNumber, string? scaleID)
        {
            try
            {
                // Checking if either serialNumber or scaleID is null or empty
                if (string.IsNullOrEmpty(serialNumber) || string.IsNullOrEmpty(scaleID))
                {
                    serialNumber = string.Empty; // Set serialNumber to empty string if null or empty
                    scaleID = string.Empty; // Set scaleID to empty string if null or empty
                }

                // Calling the repository method to get pallet records details based on serialNumber and scaleID
                List<LMC_Pallet_GetPalletRecords_Model> lPallet_PalletRecordDetails = string.IsNullOrEmpty(serialNumber) ? new List<LMC_Pallet_GetPalletRecords_Model>() : _repo.GetPalletRecordDetails(serialNumber, scaleID);

                // Creating a view model instance to pass data to the view
                LMC_Pallet_GetPalletRecords_VM oPalletGetRecordDetail = new()
                {
                    ScaleID = scaleID,
                    SerialNumber = serialNumber,
                    Lo_Pallet_PalletRecordDetails = lPallet_PalletRecordDetails
                };

                // Returning the view along with the populated view model
                return View(oPalletGetRecordDetail);
            }
            catch (Exception ex)
            {
                //Log error message to text file
                Log.Error("Error", ex.Message, ex.StackTrace);

                // Returning null in case of an exception
                return null; 
            }

        }
    }
}

LMC_Other_MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]-Label Manager Client</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LMC_Other_MVC.styles.css" asp-append-version="true" />
</head>
<body>
   <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                @* <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LMC_Other_MVC</a> *@
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @* <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li> *@
                        @* <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li> *@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="LMC_InventoryData" asp-action="Index">Inventory Data</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="LMC_InvData_RecordDetail" asp-action="Index">Record Details</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="LMC_InvData_GetInventoryData_Records" asp-action="Index">Inventory Records </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="LMC_LabelCounter_GetUploadLabelCounterRecords" asp-action="Index">Label Counter Records </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="LMC_Pallet_GetPalletRecords" asp-action="Index">Pallet Record Details</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="LMC_PrintStringLog_GetPrintStringsByPallet" asp-action="Index">String Log By Pallet</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="LMC_SyncTime_UpdateSyncTimeUploadRecords" asp-action="Index">Sync Upload Records</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="LMC_Pallet_GetNonCollected" asp-action="Index">Get Non Collected</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="LMC_PalletExact_GetPalletExactSummaryLastLabelDate" asp-action="Index">Last Label Date</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header> 
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted text-center">
        <div class="container">
            &copy @DateTime.Now.Year
             - Belgioioso Cheese Inc. @* - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> *@
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>


        